=== 00mjk/qiskit-aqua/qiskit_aqua_chemistry/drivers/configuration_schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "id": "configuration_schema.json",
    
    "type": "object",
    "properties": {
        "name":             { "type": "string" },
        "description":      { "type": "string" },
        "module":           { "type": "string" },
        "input_schema":     { "type": "object" }
    },
    "required": ["name","description","module","input_schema"],
    "additionalProperties": false
}

=== 00mjk/qiskit-aqua/qiskit_aqua_chemistry/drivers/gaussiand/configuration.json
{
    "name": "GAUSSIAN",
    "description": "Gaussian 16 Driver",
    "module": "gaussiandriver",
    "input_schema" : {
        "$schema": "http://json-schema.org/schema#",
        "id": "gaussian_schema",
        "type": "string",
        "default": "# rhf/sto-3g scf(conventional)\n\nh2 molecule\n\n0 1\nH   0.0  0.0    0.0\nH   0.0  0.0    0.735\n\n"
    }
}

=== 00mjk/qiskit-aqua/qiskit_aqua_chemistry/drivers/psi4d/configuration.json
{
    "name": "PSI4",
    "description": "PSI4 Driver",
    "module": "psi4driver",
    "input_schema" : {
        "$schema": "http://json-schema.org/schema#",
        "id": "psi4_schema",
        "type": "string",
        "default": "molecule h2 {\n  0 1\n  H  0.0 0.0 0.0\n  H  0.0 0.0 0.735\n}\n\nset {\n  basis sto-3g\n  scf_type pk\n}"
    }
}
